# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
